[Enhancement]: Update README for use as a profile README
PretendoNetwork/.github pull request #79
Opened 2024-06-26 22:19 UTC by christophe-asselin

Resolves #73 

### Changes:

Create a simpler and updated README for the Pretendo Network organization profile README. Replace contents of existing README to explain the purpose of the repository.

- [X] I have read and agreed to the [Code of Conduct](https://github.com/PretendoNetwork/Pretendo/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have read and complied with the [contributing guidelines](https://github.com/PretendoNetwork/Pretendo/blob/master/.github/CONTRIBUTING.md).
- [X] What I'm implementing was an [approved issue](../issues?q=is%3Aopen+is%3Aissue+label%3Aapproved).
- [X] I have tested all of my changes.

2024-06-26 22:21 UTC, christophe-asselin commented
Not sure about keeping the root README or what to put in it. Let me know your thoughts.

2024-06-27 18:55 UTC, jonbarrow requested changes
Thank you for taking the time to handle this! Just a few notes really, nothing major. Overall looks good, short and to the point :+1:

2024-06-27 18:55 UTC, jonbarrow commented on profile/README.md
> +* [X/Twitter](https://x.com/pretendonetwork)
We find "X/Twitter" to be a bit of a mouthful and everyone on the team still refers to it as just Twitter, so we'd prefer to still use the Twitter name and domain (for as long as it works for)

2024-06-27 18:55 UTC, jonbarrow commented on README.md
> +This special repository contains community files.
I would probably add some mention of this also being a template repository, since the files here get used as the defaults for all new repositories. And possibly the links to relevant documents like the contribution guide?

2024-06-27 18:55 UTC, jonbarrow commented on profile/README.md
> +## Official Links
Maybe this should have a link to the contribution guide? At least for now? We don't currently have our developer documentation up and running, which is where we'd ideally link to this, so it should be linked to prominently somewhere

2024-06-28 16:01 UTC, jonbarrow approved these changes

2024-06-28 16:02 UTC, jonbarrow commented
LGTM. Thanks!

2024-06-28 16:02 UTC, merged